M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-10-31T11:29:03+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-31T11:29:03+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X115.0Y-85.0
X115.0Y-115.0
X185.0Y-85.0
X185.0Y-115.0
M30
